### ISSUE TITLE
Correct repository front page

### ISSUE THREAD

**Issue by Nev-Cope** [k-kusumam/python-intermediate-inflammation#13]
Update repository comments to remove extra text
https://github.com/k-kusumam/python-intermediate-inflammation
![image](https://user-images.githubusercontent.com/112563309/198042857-62772c02-f1a7-4f30-8e37-dcabd1150df7.png)

**Comment by k-kusumam** [comment]
closed in #17

**Comment by k-kusumam** [comment]
Now its resolved in pull request #17
