### ISSUE TITLE
Remove lines of commented code

### ISSUE THREAD

**Issue by laulopezreal** [k-kusumam/python-intermediate-inflammation#5]
Code lines 64-76 are commented. Published code should not contain commented chunks.

https://github.com/k-kusumam/python-intermediate-inflammation/blob/974e3a5a0932f9a86ee9617f2cce02ddc4d768bd/tests/test_models.py#L64

**Comment by kaflesaurav** [comment]
Dougan completed, Keerthy reviewed.
