### ISSUE TITLE
Import statements should be at the beginning of the scripts rather than within the function

### ISSUE THREAD

**Issue by laulopezreal** [k-kusumam/python-intermediate-inflammation#6]
For efficiency and debugging purposes, all the import statements in python should appear at the beginning of the script.

https://github.com/k-kusumam/python-intermediate-inflammation/blob/974e3a5a0932f9a86ee9617f2cce02ddc4d768bd/tests/test_models.py#L9

**Comment by kaflesaurav** [comment]
Nina completed, Keerthy reviewed!
